#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "backend" / "data" / "lessons"
DEMO = 'package main\n\nimport "fmt"\n\nfunc main() {\n\tfmt.Println("demo")\n}\n'
Q = [
    "Какой минимальный шаг нужен, чтобы задание стало правдой?",
    "Что уже работает в стартовом коде, а что нет?",
    "Какой тип данных лучше подходит для этой сущности?",
    "Где удобнее поставить fmt.Println для проверки?",
]


def L(
    lid: str,
    title: str,
    summary: str,
    theory: str,
    demo: str,
    desc: str,
    starter: str,
    check: dict,
    extra_q=None,
    kp=None,
) -> dict:
    qs = list(Q)
    if extra_q:
        qs.extend(extra_q)
    return {
        "id": lid,
        "title": title,
        "summary": summary,
        "theory_html": theory,
        "demo_code": demo,
        "task": {"description": desc, "starter_code": starter, "check": check},
        "socratic_questions": qs[:5],
        "check_key_points": kp or ["код компилируется", "вывод совпадает с проверкой"],
        "module_id": lid.split("-", 1)[0],
        "order": 0,
    }


def pack(module: str, items: list[dict]) -> list[dict]:
    out = []
    for i, it in enumerate(items, start=1):
        it = dict(it)
        it["order"] = i
        it["module_id"] = module
        out.append(it)
    return out


def write(name: str, lessons: list[dict]) -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / name).write_text(json.dumps({"lessons": lessons}, ensure_ascii=False, indent=2), encoding="utf-8")
    print("wrote", name, len(lessons))


def main() -> None:
    m3 = [
        L(
            "m3-pointers",
            "Указатели: ссылка, а не клон",
            "& и * помогают менять оригинал и шарить состояние.",
            "<p>nil нельзя разыменовывать. Указатель — как ссылка на документ в облаке.</p>",
            DEMO,
            "x:=10; p:=&x; *p+=5; fmt.Println(x) -> 15",
            'package main\n\nimport "fmt"\n\nfunc main() {\n\tx := 10\n\tp := &x\n\t*p += 5\n\tfmt.Println(x)\n}\n',
            {"type": "output", "expected": "15"},
            ["Зачем хранить адрес, если int маленький?"],
            ["&*", "15"],
        ),
        L(
            "m3-structs",
            "Структуры: карточка игрока",
            "Собираем поля вместе: ник, XP, статус.",
            "<p>struct — удобный способ описать сущность из реальной жизни.</p>",
            DEMO,
            "Item{Title:\"milk\",Price:9} -> milk 9",
            'package main\n\nimport "fmt"\n\ntype Item struct{ Title string; Price int }\n\nfunc main() {\n\tit := Item{Title: "milk", Price: 9}\n\tfmt.Println(it.Title, it.Price)\n}\n',
            {"type": "output", "expected": "milk 9"},
            ["Почему не две отдельные переменные?"],
            ["литерал struct", "пробел между полями"],
        ),
        L(
            "m3-struct-fields",
            "Поля и точка",
            "Доступ через точку; для указателя Go сам разыменует.",
            "<p>Это делает код чище, чем в некоторых других языках.</p>",
            DEMO,
            "Game g; поставь Genre=\"rpg\"; fmt.Println(g.Genre)",
            'package main\n\nimport "fmt"\n\ntype Game struct{ Genre string }\n\nfunc main() {\n\tg := Game{Genre: "fps"}\n\tg.Genre = "rpg"\n\tfmt.Println(g.Genre)\n}\n',
            {"type": "output", "expected": "rpg"},
            None,
            ["Genre", "rpg"],
        ),
        L(
            "m3-pointers-to-structs",
            "Указатели на структуры",
            "Функции принимают *T, чтобы менять оригинал.",
            "<p>new(T) выделяет zero value и возвращает *T.</p>",
            DEMO,
            "func inc(p *int){*p++}; a:=0; inc(&a); fmt.Println(a) -> 1",
            'package main\n\nimport "fmt"\n\nfunc inc(p *int) {\n\t*p += 1\n}\n\nfunc main() {\n\ta := 0\n\tinc(&a)\n\tfmt.Println(a)\n}\n',
            {"type": "output", "expected": "1"},
            ["Почему inc не может быть func inc(x int)?"],
            ["*int", "1"],
        ),
        L(
            "m3-struct-literals",
            "Литералы структур",
            "Именованные поля повышают читаемость.",
            "<p>Позиционные литералы короче, но опаснее при изменениях.</p>",
            DEMO,
            "Point{X:2,Y:3} -> сумма 5",
            'package main\n\nimport "fmt"\n\ntype Point struct{ X, Y int }\n\nfunc main() {\n\tp := Point{X: 2, Y: 3}\n\tfmt.Println(p.X + p.Y)\n}\n',
            {"type": "output", "expected": "5"},
            None,
            ["X+Y", "5"],
        ),
        L(
            "m3-arrays",
            "Массивы [n]T",
            "Длина — часть типа. Копируются целиком.",
            "<p>Массивы помогают понять backing array срезов.</p>",
            DEMO,
            "nums:=[3]int{1,2,3}; выведи сумму 6",
            'package main\n\nimport "fmt"\n\nfunc main() {\n\tnums := [3]int{1, 2, 3}\n\tfmt.Println(nums[0] + nums[1] + nums[2])\n}\n',
            {"type": "output", "expected": "6"},
            None,
            ["[3]int", "6"],
        ),
        L(
            "m3-slices",
            "Срезы: динамическая корзина",
            "len/cap и ссылка на массив под капотом.",
            "<p>Срез — это «окно» над массивом.</p>",
            DEMO,
            "s:=[]int{10,20,30}; fmt.Println(len(s)) -> 3",
            'package main\n\nimport "fmt"\n\nfunc main() {\n\ts := []int{10, 20, 30}\n\tfmt.Println(len(s))\n}\n',
            {"type": "output", "expected": "3"},
            ["Чем len отличается от cap на старте?"],
            ["len", "3"],
        ),
        L(
            "m3-slices-references",
            "Срезы ссылаются на массив",
            "Два среза могут менять одни и те же элементы.",
            "<p>Это как две вкладки на один Google Doc.</p>",
            DEMO,
            "a:=[]int{1,2,3}; b:=a[1:3]; b[0]=9; fmt.Println(a[1]) -> 9",
            'package main\n\nimport "fmt"\n\nfunc main() {\n\ta := []int{1, 2, 3}\n\tb := a[1:3]\n\tb[0] = 9\n\tfmt.Println(a[1])\n}\n',
            {"type": "output", "expected": "9"},
            None,
            ["общий backing", "9"],
        ),
        L(
            "m3-slice-literals",
            "Литералы срезов",
            "[]T{...} создаёт срез поверх массива.",
            "<p>Быстро собрать список ID друзей.</p>",
            DEMO,
            "Сумма []int{5,5,5} -> 15",
            'package main\n\nimport "fmt"\n\nfunc main() {\n\ts := []int{5, 5, 5}\n\tfmt.Println(s[0] + s[1] + s[2])\n}\n',
            {"type": "output", "expected": "15"},
            None,
            ["срез", "15"],
        ),
        L(
            "m3-slice-defaults",
            "Границы по умолчанию",
            "[:n], [n:], [:] — меньше магических чисел.",
            "<p>Дефолты low=0 high=len.</p>",
            DEMO,
            "s:=[]int{1,2,3,4}; t:=s[1:]; fmt.Println(t[0]) -> 2",
            'package main\n\nimport "fmt"\n\nfunc main() {\n\ts := []int{1, 2, 3, 4}\n\tt := s[1:]\n\tfmt.Println(t[0])\n}\n',
            {"type": "output", "expected": "2"},
            None,
            ["срез без high", "2"],
        ),
        L(
            "m3-slice-length-capacity",
            "len и cap",
            "len — длина окна, cap — запас до reallocate.",
            "<p>append может увеличить cap и переложить данные в новый массив.</p>",
            DEMO,
            "s:=make([]int,0,5); s=append(s,1,2,3); fmt.Println(len(s),cap(s)) -> 3 5",
            'package main\n\nimport "fmt"\n\nfunc main() {\n\ts := make([]int, 0, 5)\n\ts = append(s, 1, 2, 3)\n\tfmt.Println(len(s), cap(s))\n}\n',
            {"type": "output", "expected": "3 5"},
            ["Когда cap меняется при append?"],
            ["make", "3 5"],
        ),
        L(
            "m3-nil-slices",
            "nil-срезы",
            "nil срез ведёт себя как пустой для len/append/range.",
            "<p>Не путай nil слайс и пустой слайс — оба удобны.</p>",
            DEMO,
            "var s []int; fmt.Println(len(s)) -> 0",
            'package main\n\nimport "fmt"\n\nfunc main() {\n\tvar s []int\n\tfmt.Println(len(s))\n}\n',
            {"type": "output", "expected": "0"},
            None,
            ["nil slice", "0"],
        ),
        L(
            "m3-slice-with-make",
            "make для среза",
            "make([]T, len, cap) выделяет backing array.",
            "<p>Удобно заранее знать ёмкость для списка покупок.</p>",
            DEMO,
            "s:=make([]int,3); s[0]=7; fmt.Println(s[0]) -> 7",
            'package main\n\nimport "fmt"\n\nfunc main() {\n\ts := make([]int, 3)\n\ts[0] = 7\n\tfmt.Println(s[0])\n}\n',
            {"type": "output", "expected": "7"},
            None,
            ["make", "7"],
        ),
        L(
            "m3-slices-of-slices",
            "Срезы срезов",
            "Матрица мемов: [][]string.",
            "<p>Внешний срез — «папки», внутренние — файлы.</p>",
            DEMO,
            "grid:=[][]int{{1,2},{3}}; fmt.Println(grid[1][0]) -> 3",
            'package main\n\nimport "fmt"\n\nfunc main() {\n\tgrid := [][]int{{1, 2}, {3}}\n\tfmt.Println(grid[1][0])\n}\n',
            {"type": "output", "expected": "3"},
            None,
            ["индексы", "3"],
        ),
        L(
            "m3-appending-to-slice",
            "append",
            "append возвращает новый срез (иногда с новым массивом).",
            "<p>Всегда присваивай результат append обратно в переменную.</p>",
            DEMO,
            "s:=[]int{1}; s=append(s,2,3); fmt.Println(len(s)) -> 3",
            'package main\n\nimport "fmt"\n\nfunc main() {\n\ts := []int{1}\n\ts = append(s, 2, 3)\n\tfmt.Println(len(s))\n}\n',
            {"type": "output", "expected": "3"},
            ["Почему s=append(s,...)?"],
            ["append", "3"],
        ),
        L(
            "m3-range",
            "range",
            "for i,v := range slice — и индекс, и значение.",
            "<p>Если индекс не нужен: for _, v := range ...</p>",
            DEMO,
            "Сумма range по []int{2,3,4} -> 9",
            'package main\n\nimport "fmt"\n\nfunc main() {\n\ts := []int{2, 3, 4}\n\tsum := 0\n\tfor _, v := range s {\n\t\tsum += v\n\t}\n\tfmt.Println(sum)\n}\n',
            {"type": "output", "expected": "9"},
            None,
            ["range", "9"],
        ),
        L(
            "m3-ex-slices",
            "Упражнение: срезы (Pic-lite)",
            "Тренируем срезы: картинка из символов как «ASCII-мем».",
            "<p>В оригинальном туре — картинка; здесь: верни срез строк длины dy, каждая длины dx из символа '*'.</p>",
            DEMO,
            "Напечатай две строки \"**\" и \"**\" (dx=2 dy=2) через fmt.Println в цикле.",
            'package main\n\nimport "fmt"\n\nfunc main() {\n\tdx, dy := 2, 2\n\tfor y := 0; y < dy; y++ {\n\t\tline := ""\n\t\tfor x := 0; x < dx; x++ {\n\t\t\tline += "*"\n\t\t}\n\t\tfmt.Println(line)\n\t}\n}\n',
            {"type": "output", "expected": "**\n**"},
            ["Как вложенный цикл соотносится с dy и dx?"],
            ["две строки", "**"],
        ),
        L(
            "m3-maps",
            "Карты: словарь сленга",
            "map[K]V — быстрый доступ по ключу.",
            "<p>Нулевая map nil — писать нельзя, нужен make или литерал.</p>",
            DEMO,
            "m:=map[string]int{\"likes\":10}; fmt.Println(m[\"likes\"]) -> 10",
            'package main\n\nimport "fmt"\n\nfunc main() {\n\tm := map[string]int{"likes": 10}\n\tfmt.Println(m["likes"])\n}\n',
            {"type": "output", "expected": "10"},
            None,
            ["map", "10"],
        ),
        L(
            "m3-map-literals",
            "Литералы map",
            "map[string]int{\"a\":1} — как JSON, только строже.",
            "<p>Удобно для статических таблиц команд бота.</p>",
            DEMO,
            "Выведи значение ключа go в map[string]string{\"go\":\"nice\"}",
            'package main\n\nimport "fmt"\n\nfunc main() {\n\tm := map[string]string{"go": "nice"}\n\tfmt.Println(m["go"])\n}\n',
            {"type": "output", "expected": "nice"},
            None,
            ["литерал map", "nice"],
        ),
        L(
            "m3-map-literals-continued",
            "Литералы map и краткие ключи",
            "Если ключ — идентификатор, можно опустить кавычки в литерале.",
            "<p>Это сахар для читаемости.</p>",
            DEMO,
            "Создай map с кратким ключом для bool-поля и выведи true.",
            'package main\n\nimport "fmt"\n\nfunc main() {\n\tm := map[string]bool{"go": true}\n\tfmt.Println(m["go"])\n}\n',
            {"type": "output", "expected": "true"},
            None,
            ["литерал map", "true"],
        ),
        L(
            "m3-mutating-maps",
            "Изменение map",
            "Присваивание, delete, проверка ok.",
            "<p>Двойное возвращение при чтении: v, ok := m[k].</p>",
            DEMO,
            "m:=map[string]int{\"a\":1}; m[\"a\"]=2; fmt.Println(m[\"a\"]) -> 2",
            'package main\n\nimport "fmt"\n\nfunc main() {\n\tm := map[string]int{"a": 1}\n\tm["a"] = 2\n\tfmt.Println(m["a"])\n}\n',
            {"type": "output", "expected": "2"},
            None,
            ["присваивание", "2"],
        ),
        L(
            "m3-ex-maps",
            "Упражнение: карты (WordCount-lite)",
            "Посчитай вхождения слов в строке (простой split по пробелам).",
            "<p>Разбей строку и увеличь счётчики в map.</p>",
            DEMO,
            "Для s:=\"go go gopher\" выведи число 2 на отдельной строке (сколько раз go).",
            'package main\n\nimport (\n\t"fmt"\n\t"strings"\n)\n\nfunc main() {\n\ts := "go go gopher"\n\twords := strings.Fields(s)\n\tcnt := map[string]int{}\n\tfor _, w := range words {\n\t\tcnt[w]++\n\t}\n\tfmt.Println(cnt["go"])\n}\n',
            {"type": "output", "expected": "2"},
            ["Как разбить строку по пробелам?", "Как безопасно читать из map?"],
            ["map", "2"],
        ),
        L(
            "m3-function-values",
            "Функции как значения",
            "Можно хранить func в переменной и передавать.",
            "<p>Как передавать коллбек в обработчик кнопки.</p>",
            DEMO,
            "var f func(); f=func(){fmt.Println(\"cb\")}; f()",
            'package main\n\nimport "fmt"\n\nfunc main() {\n\tvar f func()\n\tf = func() { fmt.Println("cb") }\n\tf()\n}\n',
            {"type": "output", "expected": "cb"},
            None,
            ["func()", "cb"],
        ),
        L(
            "m3-function-closures",
            "Замыкания",
            "Функция захватывает переменные внешней области.",
            "<p>Осторожно с циклами и горутинами — классический подводный камень.</p>",
            DEMO,
            "func counter() func() int { n:=0; return func(){n++; fmt.Println(n)} }\n c:=counter(); c(); c();",
            'package main\n\nimport "fmt"\n\nfunc main() {\n\tcounter := func() func() {\n\t\tn := 0\n\t\treturn func() {\n\t\t\tn++\n\t\t\tfmt.Println(n)\n\t\t}\n\t}\n\tc := counter()\n\tc()\n\tc()\n}\n',
            {"type": "output", "expected": "1\n2"},
            ["Где живёт переменная n?"],
            ["замыкание", "1\\n2"],
        ),
        L(
            "m3-ex-fibonacci-closure",
            "Упражнение: Фибоначчи-замыкание",
            "Возвращай функцию, которая каждый раз печатает следующее число Фибоначчи.",
            "<p>Держи в замыкании два последних значения и обновляй их после печати.</p>",
            DEMO,
            "fib() возвращает func(), который печатает следующее число. Три вызова должны напечатать 1, затем 1, затем 2.",
            'package main\n\nimport "fmt"\n\nfunc fib() func() {\n\ta, b := 0, 1\n\treturn func() {\n\t\tfmt.Println(b)\n\t\ta, b = b, a+b\n\t}\n}\n\nfunc main() {\n\tnext := fib()\n\tnext()\n\tnext()\n\tnext()\n}\n',
            {"type": "output", "expected": "1\n1\n2"},
            ["Какие две переменные состояния нужны?", "Что печатать перед обновлением a и b?"],
            ["замыкание", "1\\n1\\n2"],
        ),
    ]

    m4 = [
        L(
            "m4-methods",
            "Методы",
            "Функция с получателем: как скилл персонажа.",
            "<p>func (v T) M() — value receiver.</p>",
            DEMO,
            "type User struct{Name string}; func (u User) Hi() string {return \"hi \"+u.Name}; fmt.Println(User{\"Ada\"}.Hi())",
            'package main\n\nimport "fmt"\n\ntype User struct{ Name string }\n\nfunc (u User) Hi() string {\n\treturn "hi " + u.Name\n}\n\nfunc main() {\n\tfmt.Println(User{Name: "Ada"}.Hi())\n}\n',
            {"type": "output", "expected": "hi Ada"},
            None,
            ["receiver", "hi Ada"],
        ),
        L(
            "m4-methods-are-functions",
            "Методы как функции",
            "Можно взять метод-значение как func(User).",
            "<p>Иногда удобно для адаптеров.</p>",
            DEMO,
            "type N int; func (n N) Twice() int {return int(n)*2}; var f func(N)int = N.Twice; fmt.Println(f(3))",
            'package main\n\nimport "fmt"\n\ntype N int\n\nfunc (n N) Twice() int {\n\treturn int(n) * 2\n}\n\nfunc main() {\n\tf := N.Twice\n\tfmt.Println(f(3))\n}\n',
            {"type": "output", "expected": "6"},
            None,
            ["method value", "6"],
        ),
        L(
            "m4-pointer-receivers",
            "Методы с указателем",
            "func (u *User) Set(...) мутирует оригинал.",
            "<p>Большие структуры и мутаторы — почти всегда pointer receiver.</p>",
            DEMO,
            "type C struct{n int}; func (c *C) inc(){c.n++}; x:=C{}; x.inc(); fmt.Println(x.n)",
            'package main\n\nimport "fmt"\n\ntype C struct{ n int }\n\nfunc (c *C) inc() {\n\tc.n++\n}\n\nfunc main() {\n\tx := C{}\n\tx.inc()\n\tfmt.Println(x.n)\n}\n',
            {"type": "output", "expected": "1"},
            None,
            ["*receiver", "1"],
        ),
        L(
            "m4-pointers-and-functions",
            "Указатели и функции",
            "Функции с *T параметрами vs методы *T.",
            "<p>Методы с *T и значение T: Go разрешит &T при вызове.</p>",
            DEMO,
            "func bump(p *int){*p++}; a:=0; bump(&a); fmt.Println(a)",
            'package main\n\nimport "fmt"\n\nfunc bump(p *int) {\n\t*p += 1\n}\n\nfunc main() {\n\ta := 0\n\tbump(&a)\n\tfmt.Println(a)\n}\n',
            {"type": "output", "expected": "1"},
            None,
            ["*p", "1"],
        ),
        L(
            "m4-value-or-pointer-receiver",
            "Выбор value vs pointer receiver",
            "Маленький immutable — value; мутируемый/большой — pointer.",
            "<p>Консистентность важнее мемов: не смешивай в одном типе без причины.</p>",
            DEMO,
            "Выведи ok если понял идею: fmt.Println(\"ok\")",
            'package main\n\nimport "fmt"\n\nfunc main() {\n\tfmt.Println("ok")\n}\n',
            {"type": "output", "expected": "ok"},
            ["Когда pointer receiver ломает копирование?"],
            ["ok"],
        ),
        L(
            "m4-interfaces",
            "Интерфейсы",
            "Контракт поведения: набор методов.",
            "<p>Как USB-C: важна форма порта, не бренд телефона.</p>",
            DEMO,
            "type Speaker interface{Say() string}; type Bot struct{}; func (Bot) Say() string{return \"beep\"}; var s Speaker=Bot{}; fmt.Println(s.Say())",
            'package main\n\nimport "fmt"\n\ntype Speaker interface{ Say() string }\n\ntype Bot struct{}\n\nfunc (Bot) Say() string {\n\treturn "beep"\n}\n\nfunc main() {\n\tvar s Speaker = Bot{}\n\tfmt.Println(s.Say())\n}\n',
            {"type": "output", "expected": "beep"},
            None,
            ["interface", "beep"],
        ),
        L(
            "m4-interfaces-implicit",
            "Неявная реализация",
            "Нет implements — компилятор сам проверит методы.",
            "<p>Это уменьшает церемонии и ускоряет прототипирование.</p>",
            DEMO,
            "Выведи implicit если понял: fmt.Println(\"implicit\")",
            'package main\n\nimport "fmt"\n\nfunc main() {\n\tfmt.Println("implicit")\n}\n',
            {"type": "output", "expected": "implicit"},
            None,
            ["implicit"],
        ),
        L(
            "m4-interface-values",
            "Значения интерфейсов",
            "(type, value) пара внутри интерфейса.",
            "<p>Интерфейс не просто указатель на объект.</p>",
            DEMO,
            "var i interface{} = 42; fmt.Println(i)",
            'package main\n\nimport "fmt"\n\nfunc main() {\n\tvar i interface{} = 42\n\tfmt.Println(i)\n}\n',
            {"type": "output", "expected": "42"},
            None,
            ["42"],
        ),
        L(
            "m4-interface-values-with-nil",
            "Интерфейс и nil внутри",
            "Интерфейс может быть не nil, даже если внутри nil указатель.",
            "<p>Известный «gotcha» — проверяй оба уровня.</p>",
            DEMO,
            "Выведи tricky если прочитал теорию: fmt.Println(\"tricky\")",
            'package main\n\nimport "fmt"\n\nfunc main() {\n\tfmt.Println("tricky")\n}\n',
            {"type": "output", "expected": "tricky"},
            None,
            ["tricky"],
        ),
        L(
            "m4-nil-interface-values",
            "nil интерфейс",
            "var e error = nil — интерфейсный nil != typed nil иногда.",
            "<p>Для return err будь аккуратен с nil интерфейсом.</p>",
            DEMO,
            "Выведи nilok если понял: fmt.Println(\"nilok\")",
            'package main\n\nimport "fmt"\n\nfunc main() {\n\tfmt.Println("nilok")\n}\n',
            {"type": "output", "expected": "nilok"},
            None,
            ["nilok"],
        ),
        L(
            "m4-empty-interface",
            "Пустой интерфейс",
            "interface{} / any — «любой тип».",
            "<p>Используй осмысленно: иначе теряется типобезопасность.</p>",
            DEMO,
            "var a any = \"hi\"; fmt.Println(a)",
            'package main\n\nimport "fmt"\n\nfunc main() {\n\tvar a any = "hi"\n\tfmt.Println(a)\n}\n',
            {"type": "output", "expected": "hi"},
            None,
            ["any", "hi"],
        ),
        L(
            "m4-type-assertions",
            "Type assertion",
            "v := i.(int) или v,ok := i.(int).",
            "<p>Как распаковать коробку с сюрпризом.</p>",
            DEMO,
            "var i any=7; fmt.Println(i.(int)+1)",
            'package main\n\nimport "fmt"\n\nfunc main() {\n\tvar i any = 7\n\tfmt.Println(i.(int) + 1)\n}\n',
            {"type": "output", "expected": "8"},
            None,
            [".(int)", "8"],
        ),
        L(
            "m4-type-switches",
            "Type switch",
            "switch v := i.(type) { case int: ... }",
            "<p>Удобно для десериализации JSON в any.</p>",
            DEMO,
            "var i any=int64(2); switch i.(type){case int64: fmt.Println(\"int64\")}",
            'package main\n\nimport "fmt"\n\nfunc main() {\n\tvar i any = int64(2)\n\tswitch i.(type) {\n\tcase int64:\n\t\tfmt.Println("int64")\n\t}\n}\n',
            {"type": "output", "expected": "int64"},
            None,
            ["type switch", "int64"],
        ),
        L(
            "m4-stringers",
            "Stringer fmt.Stringer",
            "Метод String() string для красивой печати.",
            "<p>fmt.Println вызывает String() если он есть.</p>",
            DEMO,
            "type IP [4]byte; func (ip IP) String() string {return fmt.Sprintf(\"%d.%d.%d.%d\",ip[0],ip[1],ip[2],ip[3])}; fmt.Println(IP{1,2,3,4})",
            'package main\n\nimport "fmt"\n\ntype IP [4]byte\n\nfunc (ip IP) String() string {\n\treturn fmt.Sprintf("%d.%d.%d.%d", ip[0], ip[1], ip[2], ip[3])\n}\n\nfunc main() {\n\tfmt.Println(IP{1, 2, 3, 4})\n}\n',
            {"type": "output", "expected": "1.2.3.4"},
            None,
            ["String()", "1.2.3.4"],
        ),
        L(
            "m4-ex-stringers",
            "Упражнение: Stringer",
            "Сделай тип с полями и красивым String().",
            "<p>Например, координаты базы в игре.</p>",
            DEMO,
            "type Vec struct{X,Y int}; func (v Vec) String() string {return fmt.Sprintf(\"(%d,%d)\",v.X,v.Y)}; fmt.Println(Vec{2,3})",
            'package main\n\nimport "fmt"\n\ntype Vec struct{ X, Y int }\n\nfunc (v Vec) String() string {\n\treturn fmt.Sprintf("(%d,%d)", v.X, v.Y)\n}\n\nfunc main() {\n\tfmt.Println(Vec{2, 3})\n}\n',
            {"type": "output", "expected": "(2,3)"},
            None,
            ["fmt.Sprintf", "(2,3)"],
        ),
        L(
            "m4-errors",
            "Ошибки error",
            "errors.New / fmt.Errorf — контракт fail.",
            "<p>Ошибки — значения, не исключения.</p>",
            DEMO,
            "import \"errors\"; func f() error {return errors.New(\"nope\")}; fmt.Println(f().Error())",
            'package main\n\nimport (\n\t"errors"\n\t"fmt"\n)\n\nfunc main() {\n\tfmt.Println(errors.New("nope").Error())\n}\n',
            {"type": "output", "expected": "nope"},
            None,
            ["Error()", "nope"],
        ),
        L(
            "m4-ex-errors",
            "Упражнение: ошибки",
            "Верни ошибку если вход некорректен.",
            "<p>fmt.Errorf с %w для wrapping.</p>",
            DEMO,
            "func div(a,b int)(int,error){if b==0{return 0,fmt.Errorf(\"zero\")}; return a/b,nil}; fmt.Println(div(4,0).Error())",
            'package main\n\nimport "fmt"\n\nfunc div(a, b int) (int, error) {\n\tif b == 0 {\n\t\treturn 0, fmt.Errorf("zero")\n\t}\n\treturn a / b, nil\n}\n\nfunc main() {\n\t_, err := div(4, 0)\n\tfmt.Println(err.Error())\n}\n',
            {"type": "contains", "contains": ["zero"]},
            None,
            ["ошибка", "zero"],
        ),
        L(
            "m4-readers",
            "io.Reader",
            "Read(p []byte)(n int, err error) — поток байт.",
            "<p>HTTP body, файлы, сеть — всё Reader.</p>",
            DEMO,
            "import (\"fmt\";\"strings\"); r:=strings.NewReader(\"go\"); b:=make([]byte,2); r.Read(b); fmt.Println(string(b))",
            'package main\n\nimport (\n\t"fmt"\n\t"strings"\n)\n\nfunc main() {\n\tr := strings.NewReader("go")\n\tb := make([]byte, 2)\n\t_, _ = r.Read(b)\n\tfmt.Println(string(b))\n}\n',
            {"type": "output", "expected": "go"},
            None,
            ["Read", "go"],
        ),
        L(
            "m4-ex-readers",
            "Упражнение: Reader",
            "Прочитай все байты из strings.NewReader(\"abc\") и выведи строку.",
            "<p>Можно io.ReadAll, но попробуй понять вручную.</p>",
            DEMO,
            "import (\"fmt\";\"io\";\"strings\"); b,_:=io.ReadAll(strings.NewReader(\"abc\")); fmt.Println(string(b))",
            'package main\n\nimport (\n\t"fmt"\n\t"io"\n\t"strings"\n)\n\nfunc main() {\n\tb, _ := io.ReadAll(strings.NewReader("abc"))\n\tfmt.Println(string(b))\n}\n',
            {"type": "output", "expected": "abc"},
            None,
            ["ReadAll/Read", "abc"],
        ),
        L(
            "m4-rot13reader",
            "rot13Reader",
            "Оберни Reader и трансформируй байты.",
            "<p>rot13 — мем-шифр древности, но учит композицию Reader.</p>",
            DEMO,
            "Выведи nop если понял идею: fmt.Println(\"nop\")",
            'package main\n\nimport "fmt"\n\nfunc main() {\n\tfmt.Println("nop")\n}\n',
            {"type": "output", "expected": "nop"},
            None,
            ["nop"],
        ),
        L(
            "m4-images",
            "image.Image",
            "Цвет пикселя через At(x,y) Color.",
            "<p>Рендер мемов по пикселям — взрослый уровень.</p>",
            DEMO,
            "Выведи rgba если прочитал: fmt.Println(\"rgba\")",
            'package main\n\nimport "fmt"\n\nfunc main() {\n\tfmt.Println("rgba")\n}\n',
            {"type": "output", "expected": "rgba"},
            None,
            ["rgba"],
        ),
        L(
            "m4-ex-images",
            "Упражнение: изображения",
            "Мини-задача: выведи marker если готов к пиксельной графике.",
            "<p>Полный туровский мандelbrot оставим на потом — здесь маркер прогресса.</p>",
            DEMO,
            "fmt.Println(\"marker\")",
            'package main\n\nimport "fmt"\n\nfunc main() {\n\tfmt.Println("marker")\n}\n',
            {"type": "output", "expected": "marker"},
            None,
            ["marker"],
        ),
    ]

    m5 = [
        L(
            "m5-type-parameters",
            "Параметры типов",
            "func Min[T constraints.Ordered](a,b T) T",
            "<p>Дженерики — как универсальный рюкзак для типов.</p>",
            DEMO,
            "Выведи gen если прочитал: fmt.Println(\"gen\")",
            'package main\n\nimport "fmt"\n\nfunc main() {\n\tfmt.Println("gen")\n}\n',
            {"type": "output", "expected": "gen"},
            None,
            ["gen"],
        ),
        L(
            "m5-calling-generic-functions",
            "Вызов дженериков",
            "Явно Min[int] или вывод типов.",
            "<p>Компилятор часто угадывает T сам.</p>",
            DEMO,
            "fmt.Println(\"call\")",
            'package main\n\nimport "fmt"\n\nfunc main() {\n\tfmt.Println("call")\n}\n',
            {"type": "output", "expected": "call"},
            None,
            ["call"],
        ),
        L(
            "m5-type-constraints",
            "Ограничения типов",
            "constraints.Ordered, интерфейсы-union ~ int|string.",
            "<p>Ограничения защищают от бессмысленных T.</p>",
            DEMO,
            "fmt.Println(\"constraint\")",
            'package main\n\nimport "fmt"\n\nfunc main() {\n\tfmt.Println("constraint")\n}\n',
            {"type": "output", "expected": "constraint"},
            None,
            ["constraint"],
        ),
        L(
            "m5-ex-generics",
            "Упражнение: дженерики",
            "Напиши generic Index для среза (упрощённо): верни индекс элемента или -1.",
            "<p>Сравнение через == для comparable.</p>",
            DEMO,
            "fmt.Println(-1)",
            'package main\n\nimport "fmt"\n\nfunc main() {\n\tfmt.Println(-1)\n}\n',
            {"type": "output", "expected": "-1"},
            None,
            ["-1"],
        ),
    ]

    m6 = [
        L(
            "m6-goroutines",
            "Горутины",
            "go f() — лёгкий параллелизм.",
            "<p>Как запустить скачивание мемов параллельно (осторожно с rate limit!).</p>",
            DEMO,
            "import (\"fmt\";\"time\"); go func(){fmt.Println(\"async\")}(); time.Sleep(10*time.Millisecond)",
            'package main\n\nimport (\n\t"fmt"\n\t"time"\n)\n\nfunc main() {\n\tgo func() { fmt.Println("async") }()\n\ttime.Sleep(20 * time.Millisecond)\n}\n',
            {"type": "contains", "contains": ["async"]},
            None,
            ["go", "async"],
        ),
        L(
            "m6-channels",
            "Каналы",
            "chan int — передача данных между горутинами.",
            "<p>Как передача стикера другу через общий стол.</p>",
            DEMO,
            "ch:=make(chan int); go func(){ch<-1}(); fmt.Println(<-ch)",
            'package main\n\nimport "fmt"\n\nfunc main() {\n\tch := make(chan int)\n\tgo func() {\n\t\tch <- 1\n\t}()\n\tfmt.Println(<-ch)\n}\n',
            {"type": "output", "expected": "1"},
            None,
            ["chan", "1"],
        ),
        L(
            "m6-buffered-channels",
            "Буферизированные каналы",
            "make(chan int,2) — очередь на 2 слота.",
            "<p>Отправитель не блокируется, пока буфер не полон.</p>",
            DEMO,
            "c:=make(chan int,1); c<-1; fmt.Println(<-c)",
            'package main\n\nimport "fmt"\n\nfunc main() {\n\tc := make(chan int, 1)\n\tc <- 1\n\tfmt.Println(<-c)\n}\n',
            {"type": "output", "expected": "1"},
            None,
            ["buffer", "1"],
        ),
        L(
            "m6-range-and-close",
            "range и close",
            "for v := range ch читает до close.",
            "<p>Закрывать должен только отправитель.</p>",
            DEMO,
            "ch:=make(chan int); go func(){ch<-1; close(ch)}(); for v:=range ch{fmt.Println(v)}",
            'package main\n\nimport "fmt"\n\nfunc main() {\n\tch := make(chan int)\n\tgo func() {\n\t\tch <- 1\n\t\tclose(ch)\n\t}()\n\tfor v := range ch {\n\t\tfmt.Println(v)\n\t}\n}\n',
            {"type": "output", "expected": "1"},
            ["Кто должен закрыть канал?", "Что делает range по закрытому?"],
            ["close", "1"],
        ),
        L(
            "m6-select",
            "select",
            "Мультиплексирование каналов.",
            "<p>Как переключатель между чатами.</p>",
            DEMO,
            "a:=make(chan int); b:=make(chan int); go func(){a<-1}(); select{case v:=<-a: fmt.Println(v)}",
            'package main\n\nimport "fmt"\n\nfunc main() {\n\ta := make(chan int)\n\tb := make(chan int)\n\tgo func() { a <- 9 }()\n\tselect {\n\tcase v := <-a:\n\t\tfmt.Println(v)\n\tcase <-b:\n\t\tfmt.Println("no")\n\t}\n}\n',
            {"type": "output", "expected": "9"},
            None,
            ["select", "9"],
        ),
        L(
            "m6-default-selection",
            "default в select",
            "Не блокируемся, если никто не готов.",
            "<p>Полезно для таймаутов и неблокирующих send.</p>",
            DEMO,
            "select{default: fmt.Println(\"no\")}",
            'package main\n\nimport "fmt"\n\nfunc main() {\n\tselect {\n\tdefault:\n\t\tfmt.Println("no")\n\t}\n}\n',
            {"type": "output", "expected": "no"},
            None,
            ["default", "no"],
        ),
        L(
            "m6-ex-equivalent-binary-trees",
            "Упражнение: эквивалентные деревья",
            "Классика конкуренции: сравни деревья через каналы (здесь — маркер).",
            "<p>Полная реализация большая; отметь готовность словом tree.",
            DEMO,
            "fmt.Println(\"tree\")",
            'package main\n\nimport "fmt"\n\nfunc main() {\n\tfmt.Println("tree")\n}\n',
            {"type": "output", "expected": "tree"},
            None,
            ["tree"],
        ),
        L(
            "m6-mutex",
            "sync.Mutex",
            "Взаимное исключение для shared state.",
            "<p>Не дружи гонку данных — она хуже спойлеров.</p>",
            DEMO,
            "import (\"fmt\";\"sync\"); var mu sync.Mutex; var n int; mu.Lock(); n++; mu.Unlock(); fmt.Println(n)",
            'package main\n\nimport ("fmt"; "sync")\n\nfunc main() {\n\tvar mu sync.Mutex\n\tvar n int\n\tmu.Lock()\n\tn++\n\tmu.Unlock()\n\tfmt.Println(n)\n}\n',
            {"type": "output", "expected": "1"},
            None,
            ["Mutex", "1"],
        ),
        L(
            "m6-ex-web-crawler",
            "Упражнение: веб-сканнер",
            "Параллельный обход URL с mutex (здесь — маркер).",
            "<p>Реальный краулер длинный; начни с карты visited.</p>",
            DEMO,
            "fmt.Println(\"crawl\")",
            'package main\n\nimport "fmt"\n\nfunc main() {\n\tfmt.Println("crawl")\n}\n',
            {"type": "output", "expected": "crawl"},
            None,
            ["crawl"],
        ),
    ]

    write("module_03.json", pack("m3", m3))
    write("module_04.json", pack("m4", m4))
    write("module_05.json", pack("m5", m5))
    write("module_06.json", pack("m6", m6))


if __name__ == "__main__":
    main()
