"""Генерирует backend/data/lessons/module_XX.json из компактных описаний."""
from __future__ import annotations
import json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / 'backend' / 'data' / 'lessons'

def lesson(lid: str, title: str, order: int, module_id: str, theory: str, demo: str, task_desc: str, starter: str, check: dict) -> dict:
    return {'id': lid, 'title': title, 'theory_html': theory, 'demo_code': demo, 'task': {'description': task_desc, 'starter_code': starter, 'check': check}, 'module_id': module_id, 'order': order}

def write_module(name: str, lessons: list[dict]) -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    path = OUT_DIR / name
    path.write_text(json.dumps({'lessons': lessons}, ensure_ascii=False, indent=2), encoding='utf-8')
    print('wrote', path, 'lessons', len(lessons))

def main() -> None:
    m1: list[dict] = []
    m1.append(lesson('m1-packages', 'Пакеты: твой рюкзак с инструментами', 1, 'm1', '<p>Пакет <code>main</code> — точка входа. Функция <code>main()</code> стартует первой. Остальные пакеты — библиотеки, как приложения в телефоне: подключил — пользуешься.</p>', 'package main\n\nimport "fmt"\n\nfunc main() {\n\tfmt.Println("go go power rangers")\n}\n', 'Выведи ровно одну строку: <code>chat online</code> (как будто бот проснулся).', 'package main\n\nimport "fmt"\n\nfunc main() {\n\t// TODO\n}\n', {'type': 'output', 'expected': 'chat online'}))
    m1.append(lesson('m1-imports', 'Импорты: подключаем «приложения» стандартной библиотеки', 2, 'm1', '<p>Несколько путей импорта группируют в скобках. Неиспользуемый импорт — ошибка компиляции: Go не любит мусор в рюкзаке.</p>', 'package main\n\nimport (\n\t"fmt"\n\t"time"\n)\n\nfunc main() {\n\tfmt.Println("now:", time.Now().Format("15:04"))\n}\n', 'Импортируй fmt и выведи слово <code>meme</code> (одной строкой).', 'package main\n\nfunc main() {\n\t// TODO: import + Println\n}\n', {'type': 'output', 'expected': 'meme'}))
    m1.append(lesson('m1-exported-names', 'Экспортируемые имена: заглавная буква = публичный сторис', 3, 'm1', '<p>Это не про приватность в рантайме, а про контракт модулей: <code>fmt.Println</code> экспортируется, внутренние helper-функции часто пишут с маленькой.</p>', 'package main\n\nimport "fmt"\n\ntype mood struct {\n\tPublicEmoji  string\n\tsecretVendor string\n}\n\nfunc main() {\n\tm := mood{PublicEmoji: "🔥", secretVendor: "mom"}\n\tfmt.Println(m.PublicEmoji)\n}\n', 'Создай переменную с экспортируемым именем User (строка) и выведи её значение <code>anon</code>.', 'package main\n\nimport "fmt"\n\nfunc main() {\n\t// TODO: var User string = ...\n}\n', {'type': 'contains', 'contains': ['anon']}))
    m1.append(lesson('m1-functions', 'Функции: рецепт, который можно вызывать много раз', 4, 'm1', '<p>Сигнатура: имя, параметры, (опционально) результаты. Тело в фигурных скобках. Возврат через return.</p>', 'package main\n\nimport "fmt"\n\nfunc ping() string {\n\treturn "pong"\n}\n\nfunc main() {\n\tfmt.Println(ping())\n}\n', 'Напиши функцию greet(name string) string, которая возвращает строку Hi, <name>!. В main выведи результат для name="Ada".', 'package main\n\nimport "fmt"\n\nfunc main() {\n\t// TODO: объявить greet и вызвать\n}\n', {'type': 'output', 'expected': 'Hi, Ada!'}))
    m1.append(lesson('m1-multiple-results', 'Несколько результатов: как обмен вещами в шкатулке', 5, 'm1', '<p>Частый паттерн: (T, error). Вызывающий обязан хотя бы подумать про ошибку — мем про игнор ошибок не прокатит.</p>', 'package main\n\nimport "fmt"\n\nfunc split(sum int) (x, y int) {\n\tx = sum * 4 / 9\n\ty = sum - x\n\treturn\n}\n\nfunc main() {\n\tfmt.Println(split(17))\n}\n', 'Сделай функцию div10(n int) (int, int), которая возвращает частное и остаток от деления n на 10. Для n=47 выведи два числа через пробел: 4 7', 'package main\n\nimport "fmt"\n\nfunc main() {\n\t// TODO\n}\n', {'type': 'output', 'expected': '4 7'}))
    m1.append(lesson('m1-named-return-values', 'Именованные результаты: ленивый return', 6, 'm1', '<p>Не злоупотребляй: если функция длинная, именованные результаты ухудшают читаемость. Но для коротких хелперов — ок.</p>', 'package main\n\nimport "fmt"\n\nfunc stats() (sum int, count int) {\n\tsum = 10 + 20\n\tcount = 2\n\treturn\n}\n\nfunc main() {\n\tfmt.Println(stats())\n}\n', 'Напиши func cart() (items int, price int) где items=3, price=90 и выведи пару через пробел: 3 90', 'package main\n\nimport "fmt"\n\nfunc main() {\n\t// TODO\n}\n', {'type': 'output', 'expected': '3 90'}))
    m1.append(lesson('m1-variables', 'Переменные: коробки с наклейками', 7, 'm1', '<p>Нулевые значения: int→0, string→"", bool→false. Это не баг, это «пустой стакан».</p>', 'package main\n\nimport "fmt"\n\nfunc main() {\n\tvar nickname string\n\tvar level int\n\tfmt.Println(nickname, level)\n}\n', 'Объяви var coins int и присвой 100, затем выведи coins.', 'package main\n\nimport "fmt"\n\nfunc main() {\n\t// TODO\n}\n', {'type': 'output', 'expected': '100'}))
    m1.append(lesson('m1-variables-with-initializers', 'Инициализаторы: сразу кладём в коробку вкусняшку', 8, 'm1', '<p>Как заказ с доставкой: ты говоришь значение, Go сам понимает, это int или rune-литерал и т.д.</p>', 'package main\n\nimport "fmt"\n\nfunc main() {\n\tvar chat = "tg"\n\tvar unread = 12\n\tfmt.Println(chat, unread)\n}\n', 'var theme = "dark" и выведи theme одной строкой.', 'package main\n\nimport "fmt"\n\nfunc main() {\n\t// TODO\n}\n', {'type': 'output', 'expected': 'dark'}))
    m1.append(lesson('m1-short-var-declarations', 'Короткое := — экспресс-лайн в коде', 9, 'm1', '<p>:= объявляет новые переменные. Если хоть одна новая — можно смешивать с присваиванием существующим в многострочной форме, но обычно держи просто.</p>', 'package main\n\nimport "fmt"\n\nfunc main() {\n\tmsg := "lol"\n\tfmt.Println(msg)\n}\n', 'Используй := чтобы создать xp:=5 и вывести xp.', 'package main\n\nimport "fmt"\n\nfunc main() {\n\t// TODO\n}\n', {'type': 'output', 'expected': '5'}))
    m1.append(lesson('m1-basic-types', 'Базовые типы: int, float, bool, string — атрибуты персонажа', 10, 'm1', '<p>Есть int, int32, uint и др. В большинстве задач достаточно int. float64 для дробей.</p>', 'package main\n\nimport "fmt"\n\nfunc main() {\n\tvar online bool = true\n\tvar rate float64 = 0.99\n\tfmt.Println(online, rate)\n}\n', 'Объяви likes uint = 42 и выведи likes.', 'package main\n\nimport "fmt"\n\nfunc main() {\n\t// TODO\n}\n', {'type': 'output', 'expected': '42'}))
    m1.append(lesson('m1-zero-values', 'Нулевые значения: пустой инвентарь до первого лута', 11, 'm1', '<p>Указатели, слайсы, мапы, каналы, интерфейсы — нулевое значение nil. С ними аккуратно: вызов методов на nil интерфейсе иногда ок, на nil указателе — паника.</p>', 'package main\n\nimport "fmt"\n\nfunc main() {\n\tvar s string\n\tvar ok bool\n\tfmt.Printf("%q %v\\n", s, ok)\n}\n', 'Выведи нулевое значение int переменной через fmt.Println (одна строка с числом 0).', 'package main\n\nimport "fmt"\n\nfunc main() {\n\tvar score int\n\t// TODO: Println(score)\n}\n', {'type': 'output', 'expected': '0'}))
    m1.append(lesson('m1-type-conversions', 'Преобразование типов: явный каст, без магии как в кино', 12, 'm1', '<p>Строки и числа не конвертируются простым (int)"123". Для этого есть strconv, но здесь только числа.</p>', 'package main\n\nimport "fmt"\n\nfunc main() {\n\tvar x int32 = 9\n\tvar y int64 = int64(x) + 1\n\tfmt.Println(y)\n}\n', 'var a uint8 = 200; var b int = int(a); выведи b.', 'package main\n\nimport "fmt"\n\nfunc main() {\n\t// TODO\n}\n', {'type': 'output', 'expected': '200'}))
    m1.append(lesson('m1-type-inference', 'Вывод типов: компилятор — тихий детектив', 13, 'm1', '<p>В полях структур и в сигнатурах типы всё равно нужны явно. Inference — в основном для локальных переменных.</p>', 'package main\n\nimport "fmt"\n\nfunc main() {\n\tv := 42 // int\n\tfmt.Printf("%T\\n", v)\n}\n', 'Используй := с литералом 8.8 и выведи его тип через fmt.Printf("%T\\n", x)', 'package main\n\nimport "fmt"\n\nfunc main() {\n\t// TODO\n}\n', {'type': 'contains', 'contains': ['float64']}))
    m1.append(lesson('m1-constants', 'Константы: правила сервера, которые не меняются за матч', 14, 'm1', '<p>Константы можно группировать в блок const ( ). iota помогает нумеровать, но это в другом уроке-соседе.</p>', 'package main\n\nimport "fmt"\n\nconst MaxUploadMB = 50\n\nfunc main() {\n\tfmt.Println(MaxUploadMB)\n}\n', 'const app = "shoplist"; выведи app.', 'package main\n\nimport "fmt"\n\nfunc main() {\n\t// TODO\n}\n', {'type': 'output', 'expected': 'shoplist'}))
    m1.append(lesson('m1-numeric-constants', 'Числовые константы и iota: автонумерация как очередь в столовой', 15, 'm1', '<p>Высокая точность констант — пока они остаются «константным миром», Go может держать их как большие рациональные числа.</p>', 'package main\n\nimport "fmt"\n\nconst (\n\tA = iota\n\tB\n\tC\n)\n\nfunc main() {\n\tfmt.Println(A, B, C)\n}\n', 'Сделай const блок с iota: первый 10, дальше +1 (10,11,12). Выведи три числа через пробел.', 'package main\n\nimport "fmt"\n\nfunc main() {\n\t// TODO\n}\n', {'type': 'output', 'expected': '10 11 12'}))
    write_module('module_01.json', m1)
if __name__ == '__main__':
    main()
